version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: financetracker-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financetracker
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: financetracker-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"